### ISSUE TITLE
Can not login or register

### ISSUE THREAD

**Issue by delonborges** [nandymandy1/meven_auth_app_vuex#1]
I've followed your tutorial, on Youtube, but, I wasn't able to register or login. Also, the errors are not showing.

I'm also tried to clone/download your repo and test without any modification or changes. The results was the same (login, register problems and errors not showing)!

When I try to login, I get this error:
`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (login, line 0)`
![Captura de Tela 2019-06-18 às 22 24 07](https://user-images.githubusercontent.com/9376169/59730607-5afeda80-9219-11e9-97ac-fd7dde4b8f40.png)
```
[Log] TypeError: undefined is not an object (evaluating 'res.data')
(função anônima)
promiseReactionJob
```
![Captura de Tela 2019-06-18 às 22 33 18](https://user-images.githubusercontent.com/9376169/59730622-69e58d00-9219-11e9-849c-026a80c91128.png)

This is the code at line 68:
![Captura de Tela 2019-06-18 às 22 32 52](https://user-images.githubusercontent.com/9376169/59730627-74078b80-9219-11e9-9969-af7452876c67.png)

And, when I try to register, I get this errors:
`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (register, line 0)`
```
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'res.data')
(função anônima) - Register.vue: 101
promiseReactionJob
```
![Captura de Tela 2019-06-18 às 22 24 43](https://user-images.githubusercontent.com/9376169/59730812-2f302480-921a-11e9-8ca0-c43316b1f17d.png)

And, this is the code at line 101
![Captura de Tela 2019-06-18 às 22 25 48](https://user-images.githubusercontent.com/9376169/59730774-060f9400-921a-11e9-8922-32fcde9e2a14.png)

I really don't know if I'm doing something wrong or if it's something wrong with the codes.

Thanks in advance!
Delon.

**Comment by felipeplets** [comment]
@delonborges I'm not sure of your specific error as I could not reproduce your exact scenario. But looking in the code there is a possibility for a racing issue between the promises used in the registration method.

I've sent a PR with the solution for this other issue. Check if it also solves your scenario. 

I recommend you also to check the Mongo Collection to ensure the user is not created: 
```
use meven_auth
db.users.find().pretty()
```

If any user is created and you want to clean it, you can remove the users from the database running: 
```
db.users.remove({})
```

**Comment by delonborges** [comment]
@felipeplets, there was no user created in the database.

When I just run `node app.js` and access the localhost at 5000 port, I'm able to register and login (even though, the error messages are not showing). But, when deploying, the results are the same as when I'm running locally with the `npm run dev`, accessing localhost at 8080 port (the errors that I've posted before).

I'm passing the `npm run dev` command, because, following the tutorial, it's recommended.
Bellow it's a part of the script related to this command:
```
"server": "nodemon app.js",
"client": "npm run serve --prefix client",
"dev": "concurrently \"npm run server\" \"npm run client\""
```

Thanks for the help, anyway.

**Comment by vkms9417** [comment]
> I've followed your tutorial, on Youtube, but, I wasn't able to register or login. Also, the errors are not showing.
> 
> I'm also tried to clone/download your repo and test without any modification or changes. The results was the same (login, register problems and errors not showing)!
> 
> When I try to login, I get this error:
> `[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (login, line 0)`
> ![Captura de Tela 2019-06-18 às 22 24 07](https://user-images.githubusercontent.com/9376169/59730607-5afeda80-9219-11e9-97ac-fd7dde4b8f40.png)
> 
> ```
> [Log] TypeError: undefined is not an object (evaluating 'res.data')
> (função anônima)
> promiseReactionJob
> ```
> 
> ![Captura de Tela 2019-06-18 às 22 33 18](https://user-images.githubusercontent.com/9376169/59730622-69e58d00-9219-11e9-849c-026a80c91128.png)
> 
> This is the code at line 68:
> ![Captura de Tela 2019-06-18 às 22 32 52](https://user-images.githubusercontent.com/9376169/59730627-74078b80-9219-11e9-9969-af7452876c67.png)
> 
> And, when I try to register, I get this errors:
> `[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (register, line 0)`
> 
> ```
> [Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'res.data')
> (função anônima) - Register.vue: 101
> promiseReactionJob
> ```
> 
> ![Captura de Tela 2019-06-18 às 22 24 43](https://user-images.githubusercontent.com/9376169/59730812-2f302480-921a-11e9-8ca0-c43316b1f17d.png)
> 
> And, this is the code at line 101
> ![Captura de Tela 2019-06-18 às 22 25 48](https://user-images.githubusercontent.com/9376169/59730774-060f9400-921a-11e9-8922-32fcde9e2a14.png)
> 
> I really don't know if I'm doing something wrong or if it's something wrong with the codes.
> 
> Thanks in advance!
> Delon.

Did you solve that error

**Comment by delonborges** [comment]
> > I've followed your tutorial, on Youtube, but, I wasn't able to register or login. Also, the errors are not showing.
> > I'm also tried to clone/download your repo and test without any modification or changes. The results was the same (login, register problems and errors not showing)!
> > When I try to login, I get this error:
> > `[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (login, line 0)`
> > ![Captura de Tela 2019-06-18 às 22 24 07](https://user-images.githubusercontent.com/9376169/59730607-5afeda80-9219-11e9-97ac-fd7dde4b8f40.png)
> > ```
> > [Log] TypeError: undefined is not an object (evaluating 'res.data')
> > (função anônima)
> > promiseReactionJob
> > ```
> > 
> > 
> > ![Captura de Tela 2019-06-18 às 22 33 18](https://user-images.githubusercontent.com/9376169/59730622-69e58d00-9219-11e9-849c-026a80c91128.png)
> > This is the code at line 68:
> > ![Captura de Tela 2019-06-18 às 22 32 52](https://user-images.githubusercontent.com/9376169/59730627-74078b80-9219-11e9-9969-af7452876c67.png)
> > And, when I try to register, I get this errors:
> > `[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (register, line 0)`
> > ```
> > [Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'res.data')
> > (função anônima) - Register.vue: 101
> > promiseReactionJob
> > ```
> > 
> > 
> > ![Captura de Tela 2019-06-18 às 22 24 43](https://user-images.githubusercontent.com/9376169/59730812-2f302480-921a-11e9-8ca0-c43316b1f17d.png)
> > And, this is the code at line 101
> > ![Captura de Tela 2019-06-18 às 22 25 48](https://user-images.githubusercontent.com/9376169/59730774-060f9400-921a-11e9-8922-32fcde9e2a14.png)
> > I really don't know if I'm doing something wrong or if it's something wrong with the codes.
> > Thanks in advance!
> > Delon.
> 
> Did you solve that error

No, I didn't. But, can't reproduce anymore. I've dropped that project.
Thanks, anyway.
